"use client";
import { FormEvent,useEffect,useState } from "react";
type Project={id:number;title:string;projectUrl:string;description:string;highlights:string;contributorName:string;contributorSchool:string;contributorWechat:string};
export function OpenProjectSection(){
  const [projects,setProjects]=useState<Project[]>([]);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{fetch("/api/open-projects").then(r=>r.json()).then((d:{projects?:Project[]})=>setProjects(d.projects||[])).catch(()=>setProjects([]));},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setStatus("正在提交审核…");const form=event.currentTarget;const data=new FormData(form);const body=Object.fromEntries(["title","projectUrl","description","highlights","contributorName","contributorSchool","contributorWechat"].map(name=>[name,String(data.get(name)||"")]));try{const response=await fetch("/api/open-projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"提交失败");form.reset();setStatus("提交成功！管理员审核通过后将在这里展示。");}catch(error){setStatus(error instanceof Error?error.message:"提交失败");}finally{setBusy(false);}}
  return <section className="open-projects shell" id="open-projects"><div className="section-head"><div><p className="eyebrow"><span /> OPEN SOURCE · SHARED BY COMMUNITY</p><h2>优秀开源项目</h2></div><p>分享真正值得学习与复现的项目，<br />让每一位贡献者被看见、被记住。</p></div>
    {projects.length?<div className="project-grid">{projects.map((project,index)=><article key={project.id}><span>{String(index+1).padStart(2,"0")}</span><small>COMMUNITY PICK</small><h3>{project.title}</h3><p>{project.description}</p>{project.highlights&&<div className="project-highlight">亮点 · {project.highlights}</div>}<div className="project-author">{project.contributorName&&<b>{project.contributorName}</b>}{project.contributorSchool&&<span>{project.contributorSchool}</span>}{project.contributorWechat&&<span>微信：{project.contributorWechat}</span>}</div><a href={project.projectUrl} target="_blank" rel="noreferrer">访问开源项目 ↗</a></article>)}</div>:<div className="project-empty">第一个优秀项目正在等待你的分享。</div>}
    <details className="project-submit"><summary>＋ 分享一个优秀开源项目</summary><form onSubmit={submit}><label>项目名称<input name="title" required maxLength={200}/></label><label>项目链接<input name="projectUrl" type="url" required placeholder="https://github.com/..."/></label><label className="wide">项目介绍<textarea name="description" required maxLength={3000} placeholder="它解决什么问题？适合谁学习？"/></label><label className="wide">核心亮点（选填）<textarea name="highlights" maxLength={2000} placeholder="模型、数据、效果或复现价值"/></label><div className="identity-note wide"><b>留下你的名字，让大家记住这次分享</b><span>以下信息均为选填；填写即表示同意审核通过后在公开页面展示。</span></div><label>姓名（选填）<input name="contributorName" maxLength={80}/></label><label>学校（选填）<input name="contributorSchool" maxLength={160}/></label><label>微信号（选填）<input name="contributorWechat" maxLength={120}/></label><button disabled={busy}>{busy?"正在提交…":"提交管理员审核 →"}</button>{status&&<p className="wide submit-status">{status}</p>}</form></details>
  </section>;
}
