"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import "./preview.css";
type Member={id:number;name:string;school:string;researchDirection:string;bio:string};

export default function CollaboratorAdminPage(){
  const [key,setKey]=useState(""); const [members,setMembers]=useState<Member[]>([]); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false); const [preview,setPreview]=useState(""); const [photoY,setPhotoY]=useState(20);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  function selectPhoto(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setPreview(URL.createObjectURL(file));setPhotoY(20);}
  async function load(){ if(!key){setStatus("请先输入管理员密钥");return;} const response=await fetch("/api/collaborators"); const data=await response.json() as {collaborators?:Member[]}; setMembers(data.collaborators||[]); }
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setStatus("正在添加共创成员…");const form=event.currentTarget;try{const response=await fetch("/api/collaborators",{method:"POST",headers:{Authorization:`Bearer ${key}`},body:new FormData(form)});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"添加失败");form.reset();setPreview("");setPhotoY(20);setStatus("成员已添加并展示在合作共创区域");await load();}catch(error){setStatus(error instanceof Error?error.message:"添加失败");}finally{setBusy(false);}}
  async function remove(id:number){if(!window.confirm("确认删除这位共创成员吗？"))return;const response=await fetch(`/api/collaborators/${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${key}`}});const data=await response.json() as {error?:string};setStatus(response.ok?"成员已删除":data.error||"删除失败");if(response.ok)await load();}
  return <main className="admin-page"><div className="admin-shell"><a className="admin-back" href="/">← 返回 KIAN 学习地图</a><p className="eyebrow"><span /> CO-CREATION ADMIN DESK</p><h1>合作共创成员管理</h1><p className="admin-lead">由管理员统一添加共创伙伴的公开资料。照片将与姓名、学校、研究方向及个人简介一同展示在首页。</p>
    <form className="paper-form collaborator-form" onSubmit={submit}><label className="wide">管理员密钥<input type="password" value={key} onChange={event=>setKey(event.target.value)} required /></label><label>姓名<input name="name" maxLength={80} required placeholder="成员姓名" /></label><label>学校<input name="school" maxLength={160} required placeholder="学校 / 院系" /></label><label className="wide">研究方向<input name="researchDirection" maxLength={300} required placeholder="例如：视觉语言动作模型、机器人学习" /></label><label className="wide">个人简介<textarea name="bio" maxLength={2000} required placeholder="介绍研究经历、关注的问题与希望开展的合作" /></label><label className="wide file-field">个人照片<input name="photo" type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" required onChange={selectPhoto} /><small>选择后请在下方确认实际展示区域，确保脸部完整可见</small></label>{preview&&<div className="wide photo-preview-desk"><div><small>前台卡片实际照片区域</small><div className="photo-preview-frame"><img src={preview} alt="共创者照片预览" style={{objectPosition:`50% ${photoY}%`}}/><span>照片展示预览</span></div></div><label>调整照片上下位置<input type="range" min="0" max="100" value={photoY} onChange={event=>setPhotoY(Number(event.target.value))}/><small>拖动滑块，直到人物脸部完整显示</small></label><input type="hidden" name="photoPosition" value={`50% ${photoY}%`}/></div>}<button className="wide" disabled={busy}>{busy?"正在添加…":"确认预览并添加 →"}</button>{status&&<p className="wide form-status" role="status">{status}</p>}</form>
    <section className="review-desk"><div className="review-head"><div><small>ADMIN ONLY</small><h2>已展示成员</h2></div><button onClick={load}>刷新列表</button></div><div className="review-list">{members.map(member=><article key={member.id}><div><small>{member.school}</small><h3>{member.name}</h3><span>{member.researchDirection}</span></div><div className="review-actions"><button className="danger" onClick={()=>remove(member.id)}>删除</button></div></article>)}</div></section>
  </div></main>;
}
